name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 11 * * *'
jobs:
  test:
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - java: 8
            os: ubuntu-latest
          - java: 8
            os: windows-latest
          - java: 11
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: "${{matrix.java}}"
        distribution: temurin
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - shell: bash
      run: sbt -v "+ compile"
